# Generated by Django 3.2.25 on 2024-08-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unique_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
